<?php
error_reporting(0);
ini_set("session.cookie_httponly",1); 
require_once"360_safe3.php";
$db_host="localhost"; 
$db_user="root";
$db_pwd="root"; 

#$db_user="xbshp";
#$db_pwd="F8a9h7x209988"; 
$db_database="wbsph3";
$coding="utf8";
$servername=$HTTP_SERVER_VARS['SERVER_NAME']; 
$sub_from=$HTTP_SERVER_VARS["HTTP_REFERER"]; 
$sub_len=strlen($servername); 
$checkfrom=substr($sub_from,7,$sub_len); 
if($checkfrom!=$servername){ 
echo("警告！你正在从外部提交数据！！请立即终止！！"); 
exit; 
} 
?>